site_name: Grunt-twig-gettext documentation
site_url: http://grunt-twig-gettext.monomelodies.nl/
repo_url: https://github.com/monomelodies/grunt-twig-gettext

pages:
- Home:
    - 'Overview': 'index.md'

copyright: Copyright &copy; 2015, <a href="http://monomelodies.nl/">Marijn Ophorst</a>

